language: d
dist: xenial
sudo: required
services:
  - xvfb
env:
  - GTK=3.24

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libgtk-3-dev
      - libmount-dev
      - libsoup2.4-dev
      - libxtst-dev
      - at-spi2-core
      - openbox
      - freeglut3-dev

before_script:
  - openbox & # needs a window manager for the tests (to get focus to work)

script:
  - dub test
